# Generated by Django 3.2.9 on 2021-12-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='post_comment', to='theblog.Comment'),
        ),
    ]
