# Generated by Django 3.2.9 on 2021-11-25 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mcqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=400, null=True)),
                ('opt1', models.CharField(blank=True, max_length=100, null=True)),
                ('opt2', models.CharField(blank=True, max_length=100, null=True)),
                ('opt3', models.CharField(blank=True, max_length=100, null=True)),
                ('opt4', models.CharField(blank=True, max_length=100, null=True)),
                ('ans', models.CharField(blank=True, max_length=100, null=True)),
                ('complexity', models.CharField(choices=[('Hard', 'Hard'), ('Medium Hard', 'Medium Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='subjectNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topicNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.subjectnames')),
            ],
        ),
        migrations.CreateModel(
            name='quesSetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('passingMark', models.IntegerField(default=0)),
                ('numOfQues', models.IntegerField(default=10)),
                ('previous', models.CharField(choices=[('Previous', 'Previous'), ('Custom', 'Custom')], default='Custom', max_length=9)),
                ('privacy', models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected')], default='Public', max_length=9)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('joinedMember', models.ManyToManyField(blank=True, related_name='Joined_Member', to=settings.AUTH_USER_MODEL)),
                ('quesSets', models.ManyToManyField(blank=True, related_name='quesSetExamConnection', to='examination.mcqQuestion')),
                ('registeredMember', models.ManyToManyField(blank=True, related_name='Registered_Members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='memberExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtainedMark', models.IntegerField(default=0)),
                ('totalMark', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.quessetdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='topic',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='examination.topicnames'),
        ),
    ]
