# Generated by Django 3.2.9 on 2021-11-25 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examination', '0003_remove_quessetdetail_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quessetdetail',
            name='joinedMember',
        ),
        migrations.RemoveField(
            model_name='quessetdetail',
            name='registeredMember',
        ),
        migrations.CreateModel(
            name='sheduledExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('startTime', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('joinedMember', models.ManyToManyField(blank=True, related_name='Joined_Member', to=settings.AUTH_USER_MODEL)),
                ('quesSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.quessetdetail')),
                ('registeredMember', models.ManyToManyField(blank=True, related_name='Registered_Members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
