# Generated by Django 3.2.9 on 2021-11-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_auto_20211125_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheduledexam',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sheduledexam',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected')], default='Public', max_length=9),
        ),
    ]
