# Generated by Django 3.2.9 on 2021-11-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_auto_20211126_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheduledexam',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sheduledexam',
            name='passingMark',
            field=models.IntegerField(default=0),
        ),
    ]
