# Generated by Django 3.2.9 on 2021-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_auto_20211126_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheduledexam',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
