# Generated by Django 3.2.9 on 2021-11-26 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0008_auto_20211127_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberexamresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.sheduledexam'),
        ),
    ]
