# Generated by Django 3.2.9 on 2021-11-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0009_alter_memberexamresult_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='opt5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
